name: Arduino Build CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sketch:
          - ac_control/ir_sender/ir_sender.ino
          - ac_control/ir_receiver/ir_receiver.ino
        board:
          - fqbn: "arduino:avr:uno"
            platform: "arduino:avr"
            name: "Arduino Uno"
          - fqbn: "esp8266:esp8266:nodemcuv2"
            platform: "esp8266:esp8266"
            platform-url: "https://arduino.esp8266.com/stable/package_esp8266com_index.json"
            name: "ESP8266"
          - fqbn: "esp32:esp32:esp32"
            platform: "esp32:esp32"
            platform-url: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
            name: "ESP32"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install Arduino platform
      run: |
        if [ -n "${{ matrix.board.platform-url }}" ]; then
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls ${{ matrix.board.platform-url }}
        fi
        arduino-cli core update-index
        arduino-cli core install ${{ matrix.board.platform }}

    - name: Install IRremote library
      run: |
        arduino-cli lib install "IRremote@4.4.1"

    - name: Compile sketch for ${{ matrix.board.name }}
      run: |
        arduino-cli compile --fqbn ${{ matrix.board.fqbn }} ${{ matrix.sketch }}

    - name: Build summary
      run: |
        echo "✅ Successfully built ${{ matrix.sketch }} for ${{ matrix.board.name }}"
